In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/kaggle/input/naive-bayes-tutorial/titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
target = df.Survived
inputs = df.drop('Survived',axis='columns')

In [8]:
dummies = pd.get_dummies(inputs.Sex,dtype='int')
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [9]:
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [10]:
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [11]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [18]:
len(X_train)

712

In [19]:
len(X_test)

179

In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [25]:
model.fit(X_train,y_train)

GaussianNB()

In [26]:
model.score(X_test,y_test)

0.7486033519553073

In [28]:
model.predict(X_test[:10])

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0])

In [30]:
model.predict_proba(X_test[:10])

array([[0.0204477 , 0.9795523 ],
       [0.09026798, 0.90973202],
       [0.99252429, 0.00747571],
       [0.00451214, 0.99548786],
       [0.07577239, 0.92422761],
       [0.99250698, 0.00749302],
       [0.90093911, 0.09906089],
       [0.86745021, 0.13254979],
       [0.99215695, 0.00784305],
       [0.99098192, 0.00901808]])